import React, {PropTypes} from 'react';

const propTypes = {
};

const defaultProps = {
};

class <%= name %> extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <div>
                ---Autogenerated <%= name %>---
            </div>
        );
    }
}

<%= name %>.propTypes = propTypes;
<%= name %>.defaultProps = defaultProps;

export default <%= name %>;
