import React, { PropTypes } from 'react';

class <%= name %> extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div>
        ---AUTOGENERATED <%= name %>---
      </div>
    );
  }
}

<%= name %>.propTypes = {
};

<%= name %>.defaultProps = {
};

export default <%= name %>;
